# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: node.js 설치
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}

      - name: install npm
        run: npm install

      - name: npm build
        run: npm run build
        env:
          CI: false
  
      - uses: papeloto/action-zip@v1
        with:
          files: ./
          recursive: false
          dest: result.zip
        
      - name: S3 Sync
        uses: zdurham/s3-upload-github-action@master
        with:
           args: --acl public-read
        env:
          FILE: ./result.zip
          AWS_REGION: 'ap-northeast-2'
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Code Deploy
        run: aws deploy create-deployment --application-name oil-cd --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name oil-dev --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},bundleType=zip,key=result.zip
